### ISSUE TITLE
Run Onefetch in any of the repo's subfolders

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#129]
As suggested by @davep in #100 , It would be handy if the tool could work anywhere within a git repo, rather than only in the root of the repo.

The idea would be to search for the `.git` folder in any of the parent directories as a marker for the root of the repo and to execute onefetch on it 👍

If it fails to find it, the error message should be:

`fatal: not a git repository (or any of the parent directories): .git`

**Comment by rockisch** [comment]
Seems like the `git2` package supports this kind of usage with the `discover` method:
https://docs.rs/git2/0.10.1/git2/struct.Repository.html#method.discover

I'm opening a PR for that, although not sure I should use the error message on the description, since that's not how the other error messages are formatted.

**Comment by spenserblack** [comment]
Closed by #132
Thanks, @rockisch!

**Comment by o2sh** [comment]
The function `get_project_license` doesn't work in subfolders

**Comment by rockisch** [comment]
Damn, I ran a little test but didn't check the individual fields, my bad.

I think `git2::Repository` has some kind of method to get the root dir of the repo. I can check later when I'm home.

**Comment by davep** [comment]
Updated locally and it's working great. Just wanted to say thanks for doing this. Very much appreciated.
