### ISSUE TITLE
Adding Github/Gitlab stats to summary

### ISSUE THREAD

**Issue by HallerPatrick** [o2sh/onefetch#351]
What do you think about adding not just git related information, but also some stats about a Github/Gitlab Repo to the summary? Like stars, followers and forks.

**Comment by o2sh** [comment]
Cf. #63
IMO, the perks of having onefetch being an offline tool (better response time , usable offline) overpowers the benefits of the additional information.

**Comment by HallerPatrick** [comment]
I see that onefetch should not become bloat software.

But close to nobody is using a git repo without a vcs host like GitHub or Gitlab.

Onefetch can still be a offline tool. Onefetch is always passively including informations, e.g package manager and deps. It could just do a simple api call and look if it has internet connection and can successfully get a response from GitHub. If none of this is working just ignore it. This can also happen async too. I don't think response time should be an issue.

Code complexity wise, IMO, is not going to be a concern. A thin client wrapper around the GH api with more or less one call to get the repo stats. This can be completely modularised. We could also discuss if this is an extra feature only usable with conditional compilation.

**Comment by spenserblack** [comment]
@HallerPatrick FYI, in response to the conclusion to #63, I started [this project](https://github.com/spenserblack/repofetch) 🙂

Querying the host data brings up these questions:
- What happens if the remote and local repositories' histories differ (behind, ahead, diverged)? What would be the correct commit count and repo size? The local data or the remote data?
- Onefetch's detected language and the repo host's detected language can differ. For example, onefetch supports Markdown as a language, while GitHub doesn't include it in its language statistics ([`awesome-c`'s language is `null`](https://api.github.com/repos/oz123/awesome-c)). Should onefetch's language detection using tokei be overridden by the language detected by the API?
- These APIs often have a query limit for unauthenticated users. Should onefetch then support authentication tokens?
- Simple API calls alone may not be enough for accurate data. For example, let's say we report statistics on labels. An API call would report that this repo has 0 `enhancement` issues, because we use `Type: Enhancement`. So should onefetch assume the host's defaults, or allow the user to configure how the data is queried/interpreted?

**Comment by HallerPatrick** [comment]
All those problems are arising the more information you want to include in your summary. All I would add is Stars, Forks and Watcher. So basically all you see on the top right of a repo on Github.com projects. Everything else needs an own project like yours.  

What could be a problem is the authentication. Does the GH API allow for anonymous calls to it? If not, one could simply parse
a simple project GET requests of the [project](https://api.github.com/repos/o2sh/onefetch), which is easily done.

**Comment by geeseven** [comment]
> But close to nobody is using a git repo without a vcs host like GitHub or Gitlab.

I guess I am one of the few that uses git with no/private remotes for personal stuff or during early prototyping.

> Querying the host data brings up these questions:

I got a few myself.

- How to handle when multiple remotes have been configured?  Just loop through all of them? 
- What about selfhosted GitLab or Github Enterprises URLs that do not indicate if they are using one of these services?  i.e. git.company.com or host.your.code.com  I guess every non GitLab or GutHub URL would need to be probed.  This could lead to slowdowns due to extra checks for non GitLab or GutHub remotes.
- Should GitLab or GutHub data be displayed if the remote is flagged as a mirror or fork?  Could lead to misleading information being reported.
- Should offline be the default?

> An API call would report that this repo has 0 `enhancement` issues, because we use Type: `Enhancement`

Wouldn't a case insensitive comparison do the job?  

> All I would add is Stars, Forks and Watcher.

For this request overall, I could take it or leave it.  If this gets done, it should be limited to a small set of data.

**Comment by spenserblack** [comment]
@HallerPatrick
>Does the GH API allow for anonymous calls to it?

Yes, but it limits them, with certain limits.
- Search API calls (e.g. `is:pr is:merged`) is about 10 per minute I believe
- GraphQL *requires* authentication, I believe

If limited to stars, watchers, and forks, I think a call to `/repos/:user/:repository` would be sufficient. There is a limit on unauthenticated calls for this URL, but it's very high (1000 per minute, I think), so can only reasonably be reached if somebody was running onefetch in a loop.

So, to summarize, if only stars, watchers, and fork count are needed, authentication probably isn't necessary 🙂 

***

@geeseven 
>Wouldn't a case insensitive comparison do the job?

For this repository, yes. Sorry, I was trying to make the point that a repo owner could use *any* label as their "enhancement" label, which is why an optional alias would be necessary. Somebody could even rename the `enhancement` label to `:rocket:`, for example. However, as long as the set of data doesn't include anything about issues, my concern about this is irrelevant 🙂

**Comment by HallerPatrick** [comment]
I will probably go for a minimal implementation and will then make some performance test and will present them to you.

**Comment by o2sh** [comment]
> All I would add is Stars, Forks and Watcher.

And these stats will be retrievable only for Git repositories hosted by GitHub (and maybe GitLab ). I'm afraid these use cases won't cover the majority of our user scenarios; Git repos are universal: people can choose to self host, use TFS, BitBucket...or stay local. I agree, this would definitely be a _"Nice to have"_ feature. But unfortunately, it's also far from being  "cost free" (performance, complexity); Even if we

> do a simple api call and look if it has internet connection and can successfully get a response from GitHub. If none of this is working just ignore it. This can also happen async too. 

These will be positive for maybe 5% of the total use cases but impact 100% of them - I'm just guessing numbers here.

Besides, except for relatively big open source projects, most people don't have stars, forks or watchers on their repos.

But this is just my opinion...

> I will probably go for a minimal implementation and will then make some performance test and will present them to you.

Go for it, but no guaranty this will go to master.

**Comment by HallerPatrick** [comment]
I see that this feature request is not well received. And I don't want to push something which does not make sense in the context of onefetchs philosophy.

I mean @spenserblack [repofetch](https://github.com/spenserblack/repofetch) is already doing what we talked about. Maybe I can patch up a fork of onefetch, that uses repofetch as a subcommand or something.:D

I would therefore close this issue.
