### ISSUE TITLE
'Generate Language Badge' workflow is failling

### ISSUE THREAD

**Issue by o2sh** [o2sh/onefetch#543]
The 'Language-badge'  workflow doesn't seem to be able to find cargo: `sh: 1: cargo: not found`, which results in the generation of a badge with the value 0 for the number of supported languages.

I manually updated the language badge in f236104

**Comment by spenserblack** [comment]
I would recommend removing `spenserblack/actions-set-output` and instead using GitHub Workflow's built-in `::set-output` command.
I wrote that action so that I can set outputs with a `dotenv`-like format, but the fact that it's a docker action probably makes it more trouble than it's worth. That's probably why cargo wasn't found.

**Comment by o2sh** [comment]
It worked with your suggestion :+1: 
Thanks
