### ISSUE TITLE
Error: Could find a git repository in '.' or in any of its parents within device limits below '/mnt'

### ISSUE THREAD

**Issue by areen-c** [o2sh/onefetch#826]
### Duplicates

- [x] I have searched the existing issues

### Current behavior 😯

Error: Could find a git repository in '.' or in any of its parents within device limits below '/mnt'

### Steps to reproduce 🕹

Build from source using cargo, then type "`onefetch`" "`onefetch -a <LANGUAGE>`" and similiar command. 

For `onefetch -h `it still work. I've tried install onefetch from scoop, cargo, github releases still got the same isuue. In powershell or command line i got this error:

`Error: could not find repository from '.'; class=Repository (6); code=NotFound (-3)`

**Comment by spenserblack** [comment]
Could you give us some more details about the steps to reproduce? For example, what directory or project structure that you're running `onefetch` in?

**Comment by areen-c** [comment]
Sorry, i'm bad at explaining. I've tried running onefetch in some directory. Hope this screenshots will help.

### Onefetch installed with normal installer that running in powershell with alacrity terminal:
![2022-10-17_020136](https://user-images.githubusercontent.com/74430814/196053241-49f61c31-0549-451a-9397-531941a78034.png)

### Onefetch installed from source with cargo that running in wsl with wsltty terminal:

directory: %USERPROFILE%
![2022-10-17_020735](https://user-images.githubusercontent.com/74430814/196053391-4ef6bfc8-3051-4f7e-abdb-1f114a467ca7.png)

directory: root
![2022-10-17_021059](https://user-images.githubusercontent.com/74430814/196053477-149a4be7-e456-4ff2-8670-1adcb0a3df06.png)

**Comment by spenserblack** [comment]
I see you're running `onefetch` in your home directory, onefetch's install directory, and `E:\`. Are any of this directories git repositories? Onefetch compiles git repository data, like author stats and number of commits, so a repository is required. Here's a simple setup where onefetch should work as you expect it:
```powershell
mkdir example
cd example

# assuming git is installed
git init
echo "exit" > file.ps1
git add -A
git commit -m "Init"
onefetch
```

**Comment by areen-c** [comment]
Got it. Thanks.

**Comment by o2sh** [comment]
I assume it's because onefetch's snap  runs in `strict` confinement:

![image](https://user-images.githubusercontent.com/13710835/197406843-f3607b16-e256-4e03-a171-b32b14e7c702.png)

which means, from the [documentation](https://snapcraft.io/docs/snap-confinement):

> run in complete isolation, up to a minimal access level that’s deemed always safe. Consequently, strictly confined snaps can not access your files, network, processes or any other system resource without requesting specific access via an interface

onefetch has special read access to the `.gitconfig` files -> cf [`snapcraft.yaml`](https://github.com/o2sh/onefetch/blob/3a3b1c6c04907d5461deb6ed609a2543f5be3776/snap/snapcraft.yaml#L26)

You have 2 options:

- keep using the snap version which should work on any git repository that are within your $HOME folder.
- Install onefetch for Ubuntu via ppa, the latest version is currently available for Ubuntu 20.04, 22.04 and 22.10 --> Instruction for installation can be found [here](https://github.com/o2sh/onefetch/wiki/Installation#ubuntu-ppa)

**Comment by Ativerc** [comment]
Encountered this error on Ubuntu 24.04. 

Initially tried installing via snap. 

Got the error:

```
❯ onefetch
Error: Could not find a git repository in '.' or in any of its parents
```

Removed the snap package using `snap remove onefetch`.

And added the PPA as per the installation instructions:

and got this:

```
❯ onefetch
Error: Could not find a git repository in '.' or in any of its parents
❯ 
❯ onefetch --version
onefetch 2.21.0
❯ which onefetch
/usr/bin/onefetch
```

Can you reopen the issue? @o2sh

**Comment by o2sh** [comment]
@Ativerc Can you provide me a link to the github repo you're trying to run onefetch on?
