### ISSUE TITLE
Too many caches?

### ISSUE THREAD

**Issue by spenserblack** [o2sh/onefetch#862]
With 3 OSs and 2 Rust versions, we create 6 caches per run. A single cache can get as large as 1 GB :astonished: https://github.com/o2sh/onefetch/actions/caches

With a 10GB limit, where older caches get evicted, this means that just 1 or 2 PRs can start evicting caches for the `main` branch. Basically, I don't think the caches are living long enough to be effective.

Perhaps we should only try to use caches for stable Rust? This should result in less turnover, so that hopefully some caches will live long enough to be useful.

**Comment by o2sh** [comment]
Somehow related: 

- by switching to [`Swatinem/rust-cache`](https://github.com/Swatinem/rust-cache) for caching the build artifacts, it reduced the cache size for one CI run by a couple of hundreds MB -> https://github.com/o2sh/onefetch/actions/caches
- I also noticed that we were missing a cache step in the coverage job: fixed in bad6516, resulting in ~4 minutes saved when caching is found.

> Perhaps we should only try to use caches for stable Rust? This should result in less turnover, so that hopefully some caches will live long enough to be useful.

We could do smth like that, especially considering the fact that a "nightly" cache has a "reuse lifespan" of 1 day maximum. 
With my recent changes, we're at cache size of 4,720MB per CI run - assuming no cache reuse - which is below the 10GB limit.
So we should be able to hit the cache quite often - on stable - as long as we don't touch the `Cargo.lock` OFC.

**Comment by spenserblack** [comment]
>With my recent changes, we're at cache size of 4,720MB per CI run - assuming no cache reuse - which is below the 10GB limit.

That's a huge difference! Times like these I wish GitHub had a :astonished: comment reaction :laughing:

**Comment by spenserblack** [comment]
@o2sh I think caching is pretty good now. Should we close the issue, or were you thinking of implementing any other optimizations?
