### ISSUE TITLE
dont include node packages if they are installed

### ISSUE THREAD

**Issue by slayernominee** [o2sh/onefetch#946]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

it lists the language and the lines in the onefetch overview 

### Expected behavior 🤔

it shouldnt do that instead it should only analyze my own code

### Steps to reproduce 🕹

make a directory e.g. static (i made this for flask)
the make npm init
npm install darkreader

### Possible Solution 💡

exclude e.g. the node_modules folder name.

i think github does do this because in the github overview my project dont have 90% js part

**Comment by slayernominee** [comment]
i know its possible to exclude dirs via -e but that should be a default setting i think because that would improve the usability without worrying about any arguments

**Comment by spenserblack** [comment]
Is [this](https://github.com/slayernominee/polls/tree/main/static) the repo?

We usually rely on `.gitignore` or `.tokeignore`. Perhaps we can make our docs or `--help` message more clear about `.tokeignore`.

As you say, we can also ignore this folder by default. [Linguist achieves this with a large list of regexes to ignore](https://github.com/github/linguist/blob/c1c34e5260797b4d598f5ec76f19723bfc5a1894/lib/linguist/vendor.yml#L42). We could do something like this and make this the default `--exclude`s. It's probably better to build this behavior into tokei than onefetch, since tokei categorizes the languages, but [we may wait a while](https://github.com/o2sh/onefetch/issues?q=label%3A%22blocked%3A+tokei%22) :sweat_smile:

**Comment by slayernominee** [comment]
yes, its the repo xD

thank you a lot I will check the tokeignore file out but I think it still would be a good default setting because I dont think many people will work in the node_modules folder since its for the installed packages 🤔 

but no worries if not I still love this tool :)

**Comment by spenserblack** [comment]
Oh yeah, sorry, I meant that, if we're going to add default ignores, we *should* add it to onefetch, since it might take a while to get implemented in tokei.

**Comment by slayernominee** [comment]
so then I will close this issue because its not in the vendor file :) thanks for the help
