### ISSUE TITLE
error[E0282]: type annotations needed with latest Rust 1.67.1 (d5a82bbd2 2023-02-07)

### ISSUE THREAD

**Issue by jbolila** [o2sh/onefetch#967]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Cargo install fails with the following error:

```rust
error[E0282]: type annotations needed
   --> /home/jbolila/.cargo/registry/src/github.com-1ecc6299db9ec823/git-glob-0.4.2/src/wildmatch.rs:251:62
    |
251 | ...                   let class = &pattern.as_ref()[p_idx + 2..closing_bracket_idx - 1];
    |                                            ^^^^^^
    |
help: try using a fully qualified path to specify the expected types
    |
251 |                                         let class = &<BStr as AsRef<T>>::as_ref(pattern)[p_idx + 2..closing_bracket_idx - 1];
    |                                                      +++++++++++++++++++++++++++       ~
```

### Steps to reproduce 🕹

```bash
cargo install onefetch
```

**Comment by o2sh** [comment]
Many thanks for the report. Seems like a downstream dependency error (git-glob) 
Hopefully, It should be fixed in the next release thanks to @Byron (https://github.com/Byron/gitoxide/commit/bf6cce76475329b7abc81c5032f2a8eee92202d0).

In the meantime, you could try installing from HEAD using cargo:

`cargo install --git https://github.com/o2sh/onefetch`

**Comment by jbolila** [comment]
Thank you, it works using HEAD.

**Comment by o2sh** [comment]
[2.16.0 is now released](https://github.com/o2sh/onefetch/releases/tag/2.16.0)

`cargo install onefetch` should be working now 👍
